services:
  misp:
    build: ./mock-misp
    image: plaintext/mock-misp:1.0
    ports:
      - "8080:8080"

  vt-api:
    build: ./mock-vt
    image: plaintext/real-vt:1.0
    volumes:
      - ./feeds:/feeds:ro
    ports:
      - "8081:8081"

  lab:
    build: .
    image: plaintext/python-misp:1.0
    working_dir: /lab
    volumes:
      - ./:/lab
    environment:
      - MISP_KEY=demo-misp-key
      - MISP_URL=http://misp:8080
      - VT_URL=http://vt-api:8081
    depends_on:
      - misp
      - vt-api
    command: sleep infinity
