services:
  target:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"

  lab:
    build: .
    image: plaintext/python-webscraper:1.0
    working_dir: /lab
    volumes:
      - ./:/lab
    depends_on:
      - target
    command: sleep infinity
