services:
  lab:
    build: .
    image: plaintext/powershell-driving-tools-safely:1.0
    working_dir: /lab
    volumes:
      - ./:/lab
    command: pwsh -NoLogo -Command "Start-Sleep -Seconds 2147483647"
