#!/usr/bin/env python3
"""
Fetch a real Suricata eve.json alert set into data/alerts.json.

Source: FrankHassanabad/suricata-sample-data — eve.json alerts generated by
running Suricata over the WRCCDC-2018 (Western Regional Collegiate Cyber Defense
Competition) public PCAP. The file is a JSON array of `event_type: alert` objects.

Stdlib only (urllib) so it runs in a minimal lab container with no extra deps.
The repo also ships a small committed offline fallback in data/alerts.json, so the
lab works without network; run this only to refresh against the full real export.
"""

import datetime
import urllib.request
from pathlib import Path

SOURCE_URL = (
    "https://raw.githubusercontent.com/FrankHassanabad/"
    "suricata-sample-data/master/samples/wrccdc-2018/alerts-only.json"
)

DATA_DIR = Path(__file__).parent
OUT_FILE = DATA_DIR / "alerts.json"
PROVENANCE_FILE = DATA_DIR / "PROVENANCE.txt"


def main() -> None:
    print(f"Downloading {SOURCE_URL}")
    with urllib.request.urlopen(SOURCE_URL) as resp:  # noqa: S310 (trusted URL)
        body = resp.read()

    OUT_FILE.write_bytes(body)
    print(f"Wrote {len(body)} bytes to {OUT_FILE}")

    retrieved = datetime.date.today().isoformat()
    PROVENANCE_FILE.write_text(
        "Suricata eve.json alerts from WRCCDC-2018 PCAP, "
        "via FrankHassanabad/suricata-sample-data\n"
        f"Source URL: {SOURCE_URL}\n"
        f"Retrieved: {retrieved}\n"
    )
    print(f"Wrote provenance to {PROVENANCE_FILE}")


if __name__ == "__main__":
    main()
