services:
  samba-dc:
    build:
      context: ../02-enumeration
      dockerfile: Dockerfile.dc
    image: plaintext/corp-dc:latest
    container_name: corp-dc
    hostname: dc01
    domainname: corp.local
    environment:
      SAMBA_DOMAIN: CORP
      SAMBA_REALM: CORP.LOCAL
      SAMBA_ADMIN_PASSWORD: "C0rp@Admin!"
    networks:
      ad-net:
        ipv4_address: 10.10.0.10
    volumes:
      - ../02-enumeration/data:/data:ro
    healthcheck:
      test: ["CMD", "samba-tool", "domain", "info", "dc01.corp.local"]
      interval: 15s
      timeout: 10s
      retries: 10

  collector:
    build:
      context: ../02-enumeration
      dockerfile: Dockerfile.attacker
    image: plaintext/ad-attacker:latest
    container_name: bh-collector
    depends_on:
      samba-dc:
        condition: service_healthy
    networks:
      ad-net:
        ipv4_address: 10.10.0.30
    dns:
      - 10.10.0.10
    volumes:
      - ./data:/data
    command: sleep infinity

networks:
  ad-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
